//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Группы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Группы()
        {
            this.Студенты_в_группах = new HashSet<Студенты_в_группах>();
        }
    
        public System.Guid ID_группы { get; set; }
        public int Год_поступления { get; set; }
        public int Длительность_обучения { get; set; }
        public System.Guid Код_формы_обучения { get; set; }
        public System.Guid Код_направления_подготовки { get; set; }
        public System.Guid ID_института { get; set; }
        public string Наименование { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Студенты_в_группах> Студенты_в_группах { get; set; }
    }
}
