//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты_в_группах
    {
        public System.Guid ID_студента { get; set; }
        public System.Guid Код_формы_оплаты { get; set; }
        public System.Guid ID_группы { get; set; }
    
        public virtual Группы Группы { get; set; }
        public virtual Студенты Студенты { get; set; }
    }
}
