//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Студенты()
        {
            this.Студенты_в_группах = new HashSet<Студенты_в_группах>();
        }
    
        public System.Guid ID_студента { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public bool Пол { get; set; }
        public string Адрес_проживания { get; set; }
        public string Дата_рождения { get; set; }
        public string Уровень_владения_ИЯ { get; set; }
        public Nullable<System.DateTime> GraduationDate { get; set; }
        public Nullable<System.DateTime> WakeUpTime { get; set; }
        public Nullable<System.DateTime> InsertedDateTime { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Студенты_в_группах> Студенты_в_группах { get; set; }
        public virtual User User { get; set; }
    }
}
